// AUTO-GENERATED from the IANA tz database (pytz). Do not hand-edit;
// regenerate if you need to add a country. See tzs_00_RUNBOOK.md.
//
// Each country maps to its DISTINCT CLOCKS, not its raw IANA zone list:
// zones sharing identical winter+summer offsets are collapsed to one
// representative (US 29 zones -> 8 clocks, Canada 23 -> 10).

export const TIMEZONES_BY_COUNTRY = {
  Afghanistan: ["Asia/Kabul"],
  Albania: ["Europe/Tirane"],
  Algeria: ["Africa/Algiers"],
  "American Samoa": ["Pacific/Pago_Pago"],
  Andorra: ["Europe/Andorra"],
  Angola: ["Africa/Luanda"],
  Anguilla: ["America/Anguilla"],
  "Antigua and Barbuda": ["America/Antigua"],
  Argentina: ["America/Argentina/Buenos_Aires"],
  Armenia: ["Asia/Yerevan"],
  Aruba: ["America/Aruba"],
  Australia: [
    "Australia/Sydney",
    "Australia/Brisbane",
    "Australia/Adelaide",
    "Australia/Perth",
    "Australia/Darwin",
    "Australia/Lord_Howe",
    "Australia/Eucla",
  ],
  Austria: ["Europe/Vienna"],
  Azerbaijan: ["Asia/Baku"],
  Bahamas: ["America/Nassau"],
  Bahrain: ["Asia/Bahrain"],
  Bangladesh: ["Asia/Dhaka"],
  Barbados: ["America/Barbados"],
  Belarus: ["Europe/Minsk"],
  Belgium: ["Europe/Brussels"],
  Belize: ["America/Belize"],
  Benin: ["Africa/Porto-Novo"],
  Bermuda: ["Atlantic/Bermuda"],
  Bhutan: ["Asia/Thimphu"],
  Bolivia: ["America/La_Paz"],
  "Bosnia and Herzegovina": ["Europe/Sarajevo"],
  Botswana: ["Africa/Gaborone"],
  Brazil: [
    "America/Sao_Paulo",
    "America/Manaus",
    "America/Rio_Branco",
    "America/Noronha",
  ],
  "British Virgin Islands": ["America/Tortola"],
  Brunei: ["Asia/Brunei"],
  Bulgaria: ["Europe/Sofia"],
  "Burkina Faso": ["Africa/Ouagadougou"],
  Burundi: ["Africa/Bujumbura"],
  Cambodia: ["Asia/Phnom_Penh"],
  Cameroon: ["Africa/Douala"],
  Canada: [
    "America/Toronto",
    "America/Winnipeg",
    "America/Edmonton",
    "America/Vancouver",
    "America/Halifax",
    "America/St_Johns",
    "America/Regina",
    "America/Whitehorse",
    "America/Atikokan",
    "America/Blanc-Sablon",
  ],
  "Cape Verde": ["Atlantic/Cape_Verde"],
  "Cayman Islands": ["America/Cayman"],
  "Central African Republic": ["Africa/Bangui"],
  Chad: ["Africa/Ndjamena"],
  Chile: ["America/Santiago", "America/Coyhaique", "Pacific/Easter"],
  China: ["Asia/Shanghai", "Asia/Urumqi"],
  Colombia: ["America/Bogota"],
  Comoros: ["Indian/Comoro"],
  "Congo (Brazzaville)": ["Africa/Brazzaville"],
  "Congo (Kinshasa)": ["Africa/Kinshasa", "Africa/Lubumbashi"],
  "Cook Islands": ["Pacific/Rarotonga"],
  "Costa Rica": ["America/Costa_Rica"],
  Croatia: ["Europe/Zagreb"],
  Cuba: ["America/Havana"],
  Curaçao: ["America/Curacao"],
  Cyprus: ["Asia/Nicosia"],
  Czechia: ["Europe/Prague"],
  "Côte d'Ivoire": ["Africa/Abidjan"],
  Denmark: ["Europe/Copenhagen"],
  Djibouti: ["Africa/Djibouti"],
  Dominica: ["America/Dominica"],
  "Dominican Republic": ["America/Santo_Domingo"],
  Ecuador: ["America/Guayaquil", "Pacific/Galapagos"],
  Egypt: ["Africa/Cairo"],
  "El Salvador": ["America/El_Salvador"],
  "Equatorial Guinea": ["Africa/Malabo"],
  Eritrea: ["Africa/Asmara"],
  Estonia: ["Europe/Tallinn"],
  Eswatini: ["Africa/Mbabane"],
  Ethiopia: ["Africa/Addis_Ababa"],
  "Falkland Islands": ["Atlantic/Stanley"],
  "Faroe Islands": ["Atlantic/Faroe"],
  Fiji: ["Pacific/Fiji"],
  Finland: ["Europe/Helsinki"],
  France: ["Europe/Paris"],
  "French Guiana": ["America/Cayenne"],
  "French Polynesia": [
    "Pacific/Tahiti",
    "Pacific/Marquesas",
    "Pacific/Gambier",
  ],
  Gabon: ["Africa/Libreville"],
  Gambia: ["Africa/Banjul"],
  Georgia: ["Asia/Tbilisi"],
  Germany: ["Europe/Berlin"],
  Ghana: ["Africa/Accra"],
  Gibraltar: ["Europe/Gibraltar"],
  Greece: ["Europe/Athens"],
  Greenland: ["America/Nuuk", "America/Danmarkshavn", "America/Thule"],
  Grenada: ["America/Grenada"],
  Guadeloupe: ["America/Guadeloupe"],
  Guam: ["Pacific/Guam"],
  Guatemala: ["America/Guatemala"],
  Guernsey: ["Europe/Guernsey"],
  Guinea: ["Africa/Conakry"],
  "Guinea-Bissau": ["Africa/Bissau"],
  Guyana: ["America/Guyana"],
  Haiti: ["America/Port-au-Prince"],
  Honduras: ["America/Tegucigalpa"],
  "Hong Kong": ["Asia/Hong_Kong"],
  Hungary: ["Europe/Budapest"],
  Iceland: ["Atlantic/Reykjavik"],
  India: ["Asia/Kolkata"],
  Indonesia: ["Asia/Jakarta", "Asia/Makassar", "Asia/Jayapura"],
  Iran: ["Asia/Tehran"],
  Iraq: ["Asia/Baghdad"],
  Ireland: ["Europe/Dublin"],
  "Isle of Man": ["Europe/Isle_of_Man"],
  Israel: ["Asia/Jerusalem"],
  Italy: ["Europe/Rome"],
  Jamaica: ["America/Jamaica"],
  Japan: ["Asia/Tokyo"],
  Jersey: ["Europe/Jersey"],
  Jordan: ["Asia/Amman"],
  Kazakhstan: ["Asia/Almaty"],
  Kenya: ["Africa/Nairobi"],
  Kiribati: ["Pacific/Tarawa", "Pacific/Kanton", "Pacific/Kiritimati"],
  Kosovo: ["Europe/Belgrade"],
  Kuwait: ["Asia/Kuwait"],
  Kyrgyzstan: ["Asia/Bishkek"],
  Laos: ["Asia/Vientiane"],
  Latvia: ["Europe/Riga"],
  Lebanon: ["Asia/Beirut"],
  Lesotho: ["Africa/Maseru"],
  Liberia: ["Africa/Monrovia"],
  Libya: ["Africa/Tripoli"],
  Liechtenstein: ["Europe/Vaduz"],
  Lithuania: ["Europe/Vilnius"],
  Luxembourg: ["Europe/Luxembourg"],
  Macao: ["Asia/Macau"],
  Madagascar: ["Indian/Antananarivo"],
  Malawi: ["Africa/Blantyre"],
  Malaysia: ["Asia/Kuala_Lumpur"],
  Maldives: ["Indian/Maldives"],
  Mali: ["Africa/Bamako"],
  Malta: ["Europe/Malta"],
  "Marshall Islands": ["Pacific/Majuro"],
  Martinique: ["America/Martinique"],
  Mauritania: ["Africa/Nouakchott"],
  Mauritius: ["Indian/Mauritius"],
  Mayotte: ["Indian/Mayotte"],
  Mexico: [
    "America/Mexico_City",
    "America/Cancun",
    "America/Tijuana",
    "America/Matamoros",
    "America/Ciudad_Juarez",
    "America/Mazatlan",
  ],
  Micronesia: ["Pacific/Chuuk", "Pacific/Pohnpei"],
  Moldova: ["Europe/Chisinau"],
  Monaco: ["Europe/Monaco"],
  Mongolia: ["Asia/Ulaanbaatar", "Asia/Hovd"],
  Montenegro: ["Europe/Podgorica"],
  Montserrat: ["America/Montserrat"],
  Morocco: ["Africa/Casablanca"],
  Mozambique: ["Africa/Maputo"],
  Myanmar: ["Asia/Yangon"],
  Namibia: ["Africa/Windhoek"],
  Nauru: ["Pacific/Nauru"],
  Nepal: ["Asia/Kathmandu"],
  Netherlands: ["Europe/Amsterdam"],
  "New Caledonia": ["Pacific/Noumea"],
  "New Zealand": ["Pacific/Auckland", "Pacific/Chatham"],
  Nicaragua: ["America/Managua"],
  Niger: ["Africa/Niamey"],
  Nigeria: ["Africa/Lagos"],
  Niue: ["Pacific/Niue"],
  "North Korea": ["Asia/Pyongyang"],
  "North Macedonia": ["Europe/Skopje"],
  "Northern Mariana Islands": ["Pacific/Saipan"],
  Norway: ["Europe/Oslo"],
  Oman: ["Asia/Muscat"],
  Pakistan: ["Asia/Karachi"],
  Palau: ["Pacific/Palau"],
  Palestine: ["Asia/Gaza"],
  Panama: ["America/Panama"],
  "Papua New Guinea": ["Pacific/Port_Moresby", "Pacific/Bougainville"],
  Paraguay: ["America/Asuncion"],
  Peru: ["America/Lima"],
  Philippines: ["Asia/Manila"],
  Poland: ["Europe/Warsaw"],
  Portugal: ["Europe/Lisbon", "Atlantic/Azores"],
  "Puerto Rico": ["America/Puerto_Rico"],
  Qatar: ["Asia/Qatar"],
  Romania: ["Europe/Bucharest"],
  Russia: [
    "Europe/Kaliningrad",
    "Europe/Moscow",
    "Europe/Astrakhan",
    "Asia/Yekaterinburg",
    "Asia/Omsk",
    "Asia/Novosibirsk",
    "Asia/Irkutsk",
    "Asia/Chita",
    "Asia/Vladivostok",
    "Asia/Magadan",
    "Asia/Kamchatka",
  ],
  Rwanda: ["Africa/Kigali"],
  Réunion: ["Indian/Reunion"],
  "Saint Barthélemy": ["America/St_Barthelemy"],
  "Saint Helena": ["Atlantic/St_Helena"],
  "Saint Kitts and Nevis": ["America/St_Kitts"],
  "Saint Lucia": ["America/St_Lucia"],
  "Saint Martin": ["America/Marigot"],
  "Saint Pierre and Miquelon": ["America/Miquelon"],
  "Saint Vincent and the Grenadines": ["America/St_Vincent"],
  Samoa: ["Pacific/Apia"],
  "San Marino": ["Europe/San_Marino"],
  "Saudi Arabia": ["Asia/Riyadh"],
  Senegal: ["Africa/Dakar"],
  Serbia: ["Europe/Belgrade"],
  Seychelles: ["Indian/Mahe"],
  "Sierra Leone": ["Africa/Freetown"],
  Singapore: ["Asia/Singapore"],
  "Sint Maarten": ["America/Lower_Princes"],
  Slovakia: ["Europe/Bratislava"],
  Slovenia: ["Europe/Ljubljana"],
  "Solomon Islands": ["Pacific/Guadalcanal"],
  Somalia: ["Africa/Mogadishu"],
  "South Africa": ["Africa/Johannesburg"],
  "South Korea": ["Asia/Seoul"],
  "South Sudan": ["Africa/Juba"],
  Spain: ["Europe/Madrid", "Atlantic/Canary"],
  "Sri Lanka": ["Asia/Colombo"],
  Sudan: ["Africa/Khartoum"],
  Suriname: ["America/Paramaribo"],
  Sweden: ["Europe/Stockholm"],
  Switzerland: ["Europe/Zurich"],
  Syria: ["Asia/Damascus"],
  "São Tomé and Príncipe": ["Africa/Sao_Tome"],
  Taiwan: ["Asia/Taipei"],
  Tajikistan: ["Asia/Dushanbe"],
  Tanzania: ["Africa/Dar_es_Salaam"],
  Thailand: ["Asia/Bangkok"],
  "Timor-Leste": ["Asia/Dili"],
  Togo: ["Africa/Lome"],
  Tokelau: ["Pacific/Fakaofo"],
  Tonga: ["Pacific/Tongatapu"],
  "Trinidad and Tobago": ["America/Port_of_Spain"],
  Tunisia: ["Africa/Tunis"],
  Turkey: ["Europe/Istanbul"],
  Turkmenistan: ["Asia/Ashgabat"],
  "Turks and Caicos Islands": ["America/Grand_Turk"],
  Tuvalu: ["Pacific/Funafuti"],
  "U.S. Virgin Islands": ["America/St_Thomas"],
  Uganda: ["Africa/Kampala"],
  Ukraine: ["Europe/Simferopol", "Europe/Kyiv"],
  "United Arab Emirates": ["Asia/Dubai"],
  "United Kingdom": ["Europe/London"],
  "United States": [
    "America/New_York",
    "America/Chicago",
    "America/Denver",
    "America/Phoenix",
    "America/Los_Angeles",
    "America/Anchorage",
    "Pacific/Honolulu",
    "America/Adak",
  ],
  Uruguay: ["America/Montevideo"],
  Uzbekistan: ["Asia/Samarkand"],
  Vanuatu: ["Pacific/Efate"],
  "Vatican City": ["Europe/Vatican"],
  Venezuela: ["America/Caracas"],
  Vietnam: ["Asia/Ho_Chi_Minh"],
  Yemen: ["Asia/Aden"],
  Zambia: ["Africa/Lusaka"],
  Zimbabwe: ["Africa/Harare"],
  "Åland Islands": ["Europe/Mariehamn"],
};

// Friendly names for zones people know by region rather than city.
export const ZONE_LABELS = {
  "America/Adak": "Hawaii–Aleutian Time",
  "America/Anchorage": "Alaska Time",
  "America/Atikokan": "Eastern Time — no DST",
  "America/Blanc-Sablon": "Atlantic Time — no DST",
  "America/Chicago": "Central Time",
  "America/Denver": "Mountain Time",
  "America/Edmonton": "Mountain Time",
  "America/Halifax": "Atlantic Time",
  "America/Los_Angeles": "Pacific Time",
  "America/New_York": "Eastern Time",
  "America/Phoenix": "Mountain Time — Arizona (no DST)",
  "America/Regina": "Central Time — Saskatchewan (no DST)",
  "America/St_Johns": "Newfoundland Time",
  "America/Toronto": "Eastern Time",
  "America/Vancouver": "Pacific Time",
  "America/Whitehorse": "Yukon Time (no DST)",
  "America/Winnipeg": "Central Time",
  "Australia/Adelaide": "Central (SA)",
  "Australia/Brisbane": "Eastern — Queensland (no DST)",
  "Australia/Darwin": "Central — NT (no DST)",
  "Australia/Hobart": "Eastern (TAS)",
  "Australia/Melbourne": "Eastern (VIC)",
  "Australia/Perth": "Western Time",
  "Australia/Sydney": "Eastern (NSW)",
  "Pacific/Auckland": "New Zealand Time",
  "Pacific/Chatham": "Chatham Islands",
  "Pacific/Honolulu": "Hawaii Time (no DST)",
};
